#pragma once
// Generated from the Dead Island uest/localization data.
namespace DeadIslandData {
struct QuestEntry { const char* id; const char* title; int storyPercent; };
struct LevelEntry { const char* id; const char* title; };
inline constexpr QuestEntry kQuests[] = {
    {"Intro_Movies", "Intro Movies", 0},
    {"Hotel_Prologue", "Chaos Overture", 0},
    {"__ACT1A_X_Phase000", "Chaos Overture", 1},
    {"ACT1A_ResortStart", "Dawn of the Dead", 2},
    {"ACT1A_SaveSinamoi", "Blood on the Sand", 3},
    {"__ACT1A_SaveSinamoi_END", "Blood on the Sand", 5},
    {"ACT1A_TalkToSinamoi01", "Passport to Life", 6},
    {"ACT1A_WalkieTalkies", "Passport to Life", 7},
    {"__ACT1A_WalkieTalkiesEnd", "Passport to Life", 8},
    {"ACT1A_TalkToSinamoi02", "Exodus", 9},
    {"ACT1A_ClearRescueHub", "Exodus", 10},
    {"__ACT1A_X_Phase001", "Exodus", 11},
    {"ACT1A_Sinamoi_Busy", "To Kill Time", 12},
    {"ACT1A_TalkToSinamoi03", "A Piece of Cake", 14},
    {"ACT1A_Sinamoi_FoodBars", "A Piece of Cake", 15},
    {"ACT1A_TalkToSinamoi04", "Seek'n'Loot", 16},
    {"ACT1A_Sinamoi_FoodSupplies", "Seek'n'Loot", 17},
    {"ACT1A_TalkToSinamoi05", "Born to be Wild", 18},
    {"ACT1A_GoToParkingLot", "Born to be Wild", 19},
    {"ACT1A_BackWithVanToHub", "Born to be Wild", 22},
    {"ACT1A_TalkToSinamoi06", "Black Hawk Down", 23},
    {"ACT1A_SinamoiHelicopter", "Black Hawk Down", 24},
    {"__ACT1A_SinamoiHelicopter_Back", "Black Hawk Down", 25},
    {"ACT1A_TalkToSinamoi07", "Misery Wagon", 26},
    {"ACT1A_Mechanic", "Misery Wagon", 27},
    {"ACT1A_Mechanic_Protect", "Only the Strong Survive", 28},
    {"ACT1A_TalkToJin01", "On the Road", 30},
    {"ACT1A_ToTheCity", "On the Road", 31},
    {"ACT1A_BackFromCity", "It's Never Too Late", 60},
    {"ACT1A_TalkToSinamoi08", "Bird on the Roof", 61},
    {"ACT1A_GoToHotel", "Bird on the Roof", 62},
    {"ACT1A_BackToLG", "Home Sweet Home", 64},
    {"ACT1A_Bunker", "Devastator", 65},
    {"ACT1A_FindMowenInJungle", "Welcome to the jungle", 66},
    {"ACT1A_BoatSupplies", "Back in Black", 88},
    {"ACT1A_BackToLab", "Hide and Seek", 89},
    {"ParkingLot_FindVAN", "Born to be Wild", 20},
    {"ACT2A_LevelStart", "On the Road", 32},
    {"ACT2A_DefendChurch", "Ram on Heaven's Door", 33},
    {"ACT2A_GoToChurch", "Sacred Silence", 34},
    {"ACT2A_PumpFactory", "Drowned Hope", 35},
    {"ACT2A_PumpFactory_Ends", "Drowned Hope", 36},
    {"ACT2A_PumpFactory_Hydrants", "Drop by Drop", 38},
    {"ACT2A_GoToACT2B", "Keep the Faith", 39},
    {"ACT2A_EscortJoseph", "Way of Salvation", 40},
    {"__ACT2A_HideJoseph", "Way of Salvation", 42},
    {"Slums_GoToChurch_FromCityHallB", "Bitter Return", 53},
    {"ACT2A_FindJin", "Lady in Trouble", 55},
    {"ACT2A_AfterPolicestation", "Lady in Trouble", 58},
    {"ACT2A_BackToACT1A", "Faith Will Move Mountains", 59},
    {"ACT2A_BoatSupplies", "Boat supplies", 86},
    {"__ACT2A_HideJinAndTruck", "Faith Will Move Mountains", 0},
    {"__ACT2A_HideMowenAndBoat", "Boat supplies", 0},
    {"PoliceStation_JinRescue", "Lady in Trouble", 57},
    {"Reza_Q1", "Imprisoned For Life", 57},
    {"__Reza_Q1_Hide", "Imprisoned For Life", 58},
    {"Patrick_Q1_BillDead", "Paperwork", 59},
    {"Tim_Q1_BringDocuments", "Matter of Justice", 0},
    {"Sewers_EscortJoseph", "Way of Salvation", 41},
    {"Sewers_OpenSluices", "Let the Waters Flow", 42},
    {"Sewers_GoToACT2B", "Let the Waters Flow", 43},
    {"Sewers_GoToMarket", "Supermarket Journey", 48},
    {"Sewers_BridgeSupplies", "Bitter Return", 50},
    {"Sewers_GoToChurch_FromCityHallB", "Bitter Return", 52},
    {"Sewers_GoToPoliceStation", "Lady in Trouble", 56},
    {"_RiseZombies", "On the Road", 33},
    {"__Sewers_SwitchCityPortals", "Supermarket Journey", 50},
    {"__GoToPolicestationTest_Sewers", "On the Road", 33},
    {"__Skull_Ornage_Actv", "Supermarket Journey", 0},
    {"__Skull_Purple_Start", "Way of Salvation", 41},
    {"ACT2B_CityHall", "Head Against the Wall", 44},
    {"Sewers_EscortJoshToMarket", "Supermarket Journey", 45},
    {"__Sewers_ToMarket_Police", "Supermarket Journey", 47},
    {"ACT2B_BridgeSupplies_BackSewers", "Bitter Return", 51},
    {"Market_FindSupplies", "Supermarket Journey", 49},
    {"ACT3A_FindMowen", "Red Sky at Dawn", 67},
    {"ACT3A_MatuteroPackage", "Chasing Shadows", 68},
    {"ACT3A_MatuteroPackage_Hide", "Chasing Shadows", 69},
    {"ACT3A_BackBoat", "Soldier of Fortune", 70},
    {"ACT3A_BackBoat_Hide", "Soldier of Fortune", 72},
    {"ACT3A_GoToMowen", "King of the Swamp", 73},
    {"ACT3A_GoToTheLab", "River Trip", 74},
    {"ACT3B_Lab1", "River Trip", 75},
    {"ACT3B_West_research_001", "River Trip", 76},
    {"ACT3B_WestNatives_001", "River Trip", 77},
    {"ACT3B_WestNatives_002", "River Trip", 78},
    {"ACT3B_West_research_002", "Demonic Science", 80},
    {"ACT3B_Opes_Help", "Pure Blood", 81},
    {"__ACT3B_OpeCatacombs", "Heart of Darkness", 82},
    {"ACT3B_SacredPlace", "Daughter of Hope", 84},
    {"ACT3B_VoiceTalkToMowen", "Hard Talk", 85},
    {"ACT3B_BackToLab", "No Time to Talk", 90},
    {"ACT3C_SacredPlace", "Sacred Place", 83},
    {"ACT4A_Prison_FinalFight", "On the Edge", 99},
    {"DI_FINAL", "On the Edge", 100},
    {"ACT4B_Prison", "Titus Andronikus", 91},
    {"ACT4B_EarnTitussTrust002", "The Green Mile", 92},
    {"ACT4B_EarnTitussTrust001_A", "The Green Mile", 93},
    {"ACT4B_EarnTitussTrust001", "Full Metal Jacket", 94},
    {"ACT4B_EarnTitussTrust003", "Dante's Kitchen", 95},
    {"ACT4B_WayToBlockC", "Devil's Labyrinth", 97},
    {"ACT4B_TakeAfterWhite", "Chasing the White Rabbit", 98},
    {"Nick_Q1_Interior", "A New Broom Sweeps Clean", 0},
    {"Nick_Q2", "Spy Game", 1},
    {"Nick_Q5", "Spy Game", 0},
    {"Haus_Q1", "Fast Aid", 1},
    {"Haus_Q1_Finish", "Fast Aid", 0},
    {"Patrick_Q1", "Paperwork", 58},
    {"Patrick_Q1_Finish", "Paperwork", 60},
    {"Ryan_Q1_Interior", "Blood Ties", 0},
    {"Tim_Q2_BringGun", "Judgement Day", 0},
    {"Mugambe_Q1_Interior", "In Cold Blood", 0},
    {"Alice_Q1_Interior", "Uninvited Guests", 0},
    {"Stan_Q1_Interior", "Grasp All, Lose All", 0},
    {"Jared_Q2_BInterior", "A Tough Nut to Crack", 0},
    {"__Skull_Blue_Start", "Chaos Overture", 1},
    {"__Skull_Purple_Actv", "Way of Salvation", 42},
    {"RWhite_City_001", "RWhite City 001", -1},
    {"RWhite_Jungle_001", "RWhite Jungle 001", -1},
    {"__ACT1A_X_Phase002", "Chaos Overture", -1},
    {"Steffen_Q1", "The Lost", -1},
    {"__Steffen_Q1_End", "The Lost", -1},
    {"Dominic_QF01", "On the Air", -1},
    {"__Dominic_QF01_Change", "On the Air", -1},
    {"__Dominic_QF01_Clear", "On the Air", -1},
    {"__Dominic_QF01_Hide", "On the Air", -1},
    {"Mike_QF02", "Ashes to Ashes", -1},
    {"Mike_QF03", "Fiery Drinks", -1},
    {"ACT1A_BobbyAmbulatory", "Bloody Health Service!", -1},
    {"__ACT1A_BobbyInToAmbulatory", "Bloody Health Service!", -1},
    {"ACT1A_BobbyBag", "Life in the bag", -1},
    {"__ACT1A_BobbyBag_Clear", "Life in the bag", -1},
    {"ACT1A_Car_Repair", "Lazarus Rising", -1},
    {"__ACT1A_Car_Repair_End", "Lazarus Rising", -1},
    {"__ACT1A_Car_Repair_Clear", "Lazarus Rising", -1},
    {"Max_Q1", "Family Matters", -1},
    {"Jeannine_Q1", "My Precious...", -1},
    {"__ACT1A_X_Phase003", "Exodus", -1},
    {"James_Q1", "Knockin' on Heaven's Door", -1},
    {"__Colin_End", "Knockin' on Heaven's Door", -1},
    {"__LH_Survivor_039", "Knockin' on Heaven's Door", -1},
    {"James_Q1_Accomplished", "Knockin' on Heaven's Door", -1},
    {"James_Q2", "Counsel of Despair", -1},
    {"__James_Q2_Clear", "Counsel of Despair", -1},
    {"Darvin_Q1", "A Ray of Hope", -1},
    {"Darvin_Q1_End", "A Ray of Hope", -1},
    {"__Darvin_Q1_Clear", "A Ray of Hope", -1},
    {"Mick_Q1", "Tell Me Where It Hurts", -1},
    {"__Mick_Q1_End", "Tell Me Where It Hurts", -1},
    {"Monica_Q1", "Nighthawk", -1},
    {"__Monica_Q1_Over", "Nighthawk", -1},
    {"Trevor_Q1", "Light My Fire", -1},
    {"__Trevor_Q1_End", "Light My Fire", -1},
    {"Nikolai_Q2", "A Voice from Above the Sky", -1},
    {"__Nikolai_Q2_End", "A Voice from Above the Sky", -1},
    {"Freddie_Q1", "Gold Digger", -1},
    {"__Freddie_Q1_Things", "Gold Digger", -1},
    {"Anne_Q1", "Toy Story", -1},
    {"__Anne_Q1_Clean", "Toy Story", -1},
    {"Jennifer_Q1", "Two Hearts", -1},
    {"__Jose_Q1", "Caged Heat", -1},
    {"__Jose_Q1_End", "Caged Heat", -1},
    {"__Bunker02", "Caged Heat", -1},
    {"__Skull_Green_Start", "Chaos Overture", -1},
    {"__Skull_Brown_Start", "Chaos Overture", -1},
    {"__Skull_Brown_Actv", "Chaos Overture", -1},
    {"__Skull_Blue_Actv", "Chaos Overture", -1},
    {"__Richard_Q1", "Bad Day at the Beach", -1},
    {"__Richard_Q1_End", "Chaos Overture", -1},
    {"Richard_Q2", "House Full of Surprises", -1},
    {"__Richard_Q2_End", "House Full of Surprises", -1},
    {"Roger_Q1", "Bloody Valentine", -1},
    {"__Jessica_End", "Bloody Valentine", -1},
    {"__Roger_Q1_End", "Bloody Valentine", -1},
    {"__Jessica_Teleport", "Bloody Valentine", -1},
    {"Stanley_Q1", "Out of Stock", -1},
    {"__Stanley_Q1_End", "Out of Stock", -1},
    {"Laurie_Q1", "Crash", -1},
    {"__Laurie_Q1_End", "Crash", -1},
    {"__Laurie_Q1_Clear", "Crash", -1},
    {"Omar_Q1", "Hit and Run", -1},
    {"Omar_Q2", "Omar Escort", -1},
    {"__Omar_Q2_Infecteds", "Hit and Run", -1},
    {"__Omar_Q2_End", "Omar Escort", -1},
    {"Harlan_Q0", "Ashes to Ashes", -1},
    {"Harlan_Q3", "Make Yourself at Home", -1},
    {"Harlan_Q1", "Fluid Necessity", -1},
    {"Harlan_Q4", "Death in the Glass", -1},
    {"__Alfred_Q1", "ShowTime", -1},
    {"__Alfred_Q1_Hide", "Chaos Overture", -1},
    {"__Steve_Q1", "Help Needed", -1},
    {"__Steve_Q1_End", "Exodus", -1},
    {"Luke_Q1", "Too Much Sugar", -1},
    {"__Luke_Q1_End", "Too Much Sugar", -1},
    {"__ACT1A_Shops", "Exodus", -1},
    {"Svetlana_Q1", "Time for Booze", -1},
    {"Kim_Q1", "Nectar of Life", -1},
    {"Ned_Q1", "Wind in the Stomach", -1},
    {"__ACT1A_Survivor001", "Survivor", -1},
    {"__ACT1A_Survivor001_End", "Chaos Overture", -1},
    {"__ACT1A_Survivor001_Clear", "Chaos Overture", -1},
    {"__ACT1A_Bloody_man_Pool", "Passport to Life", -1},
    {"__ACT1A_Bloody_man_Pool_Clear", "Passport to Life", -1},
    {"__ACT1A_Survivor_002", "Chaos Overture", -1},
    {"__ACT1A_AfterNikolaiInfecteds", "Black Hawk Down", -1},
    {"ACT1A_ElectricPool_001", "Waterdance", -1},
    {"__ACT1A_ElectricPool_Infecteds", "Waterdance", -1},
    {"__ACT1A_TunnelLadder", "Chaos Overture", -1},
    {"__ACT1A_SecondGasstation_Door", "Chaos Overture", -1},
    {"__ACT1A_SecondGasstation_Bus_Exp", "Chaos Overture", -1},
    {"__ACT1A_SecongGasstation_Magazine_Gate", "Chaos Overture", -1},
    {"__ACT1A_SG_Roof_Thug", "Chaos Overture", -1},
    {"__ACT1A_Magazine_Door_Unlock", "Chaos Overture", -1},
    {"__ACT1A_Magazine2_Door_Unlock", "Chaos Overture", -1},
    {"__ACT1A_SuppliesDelivered", "Faith Will Move Mountains", -1},
    {"__ACT1A_MowenInResort", "Boat supplies", -1},
    {"__ACT1A_FirstGasstation_Padlock", "Chaos Overture", -1},
    {"__ACT1A_FirstGasstation_Gate01", "Chaos Overture", -1},
    {"__ACT1A_FirstGasstation_Gate02", "Chaos Overture", -1},
    {"__ACT1A_Bungalow01_Action", "Chaos Overture", -1},
    {"__ACT1A_Bungalow02_Action", "Chaos Overture", -1},
    {"__ACT1A_Bungalow03_Action", "Chaos Overture", -1},
    {"__ACT1A_Pool_Bar002_door01", "To Kill Time", -1},
    {"__ACT1A_PL_Out", "Born to be Wild", -1},
    {"__ACT1A_Beach_Infecteds", "Exodus", -1},
    {"__ACT1A_CaveCrates", "Chaos Overture", -1},
    {"__ACT1A_EstateCrates", "Chaos Overture", -1},
    {"__ACT1A_Bunker04", "Chaos Overture", -1},
    {"__ACT1A_ZombiePorn", "Chaos Overture", -1},
    {"__ACT1A_Gun01", "Chaos Overture", -1},
    {"__ACT1A_Gun02", "Chaos Overture", -1},
    {"Alfred_Q2", "Chaos Overture", -1},
    {"Ojibon_Q1", "Cat on the roof", -1},
    {"__Ojibon_hide", "Cat on the roof", -1},
    {"Bruno_Q1", "Fortress of God", -1},
    {"Bruno_Q2", "Three Nails", -1},
    {"Rian_Q1", "Divine Light", -1},
    {"Owain_Q1", "Six Feet Under", -1},
    {"__Qwain_Q1_After", "Six Feet Under", -1},
    {"Jack_Q1", "Picture of Bliss", -1},
    {"ACT2A_KillGraveyardZombies", "Bury the Dead", -1},
    {"Howard_Q1", "Last Chance on the Wall", -1},
    {"Carla_Q1", "One Last Breath", -1},
    {"Deanna_Q1", "One Foot in the Grave", -1},
    {"Haus_Q1_ext", "Fast Aid", -1},
    {"Matt_Q1_pre", "On the Road", -1},
    {"Matt_Q1", "Shop's Closed", -1},
    {"__Matt_Q1_Hide", "Shop's Closed", -1},
    {"Ryan_Q1", "Blood Ties", -1},
    {"Ryan_Q1_Escort", "Back to Brother", -1},
    {"__Ryan_Q1_Escort_finish", "Back to Brother", -1},
    {"__Frang_pre", "Drowned Hope", -1},
    {"Frank_Q1", "Godless Entities", -1},
    {"__Frank_Q1", "Godless Entities", -1},
    {"Carl_Q1", "Radio Ga Ga", -1},
    {"Terrance_Q1", "Last Will", -1},
    {"__Terrance_Q1_post", "Last Will", -1},
    {"Nick_Q1", "A New Broom Sweeps Clean", -1},
    {"__Nick_Q1_BackFromInterior", "A New Broom Sweeps Clean", -1},
    {"Simon_Q1", "Simon Says...", -1},
    {"__Simon_Q1_move", "Simon Says...", -1},
    {"Juri_Q1", "A Voice from Above the Sky", -1},
    {"Florencio_Q1", "Spicy Drinks", -1},
    {"__Florencio_Q2", "Spicy Drinks", -1},
    {"Mugambe_Q1", "In Cold Blood", -1},
    {"Mugambe_Q1_End", "In Cold Blood", -1},
    {"Jared_Q1", "A Tough Nut to Crack", -1},
    {"Jared_Q1_AfterInt", "A Tough Nut to Crack", -1},
    {"__Jared_Q1_Finish", "A Tough Nut to Crack", -1},
    {"Teresa_Q1", "Alcohol for Theresa", -1},
    {"Alicia_Q1", "Uninvited Guests", -1},
    {"__Alicia_Q1_Finish", "Uninvited Guests", -1},
    {"Stan_Q1", "Grasp All, Lose All", -1},
    {"Stan_Q1_Finish", "Grasp All, Lose All", -1},
    {"__Stan_Q1_Hide", "Grasp All, Lose All", -1},
    {"Tim_Q1", "Matter of Justice", -1},
    {"Tim_Q1_Finish", "Matter of Justice", -1},
    {"Tim_Q2", "Judgement Day", -1},
    {"Tim_Q2_Finish", "Judgement Day", -1},
    {"__ACT2A_Movie_FlyBy_Part1", "On the Road", -1},
    {"Vang_Q1_encounter01", "Drop by Drop", -1},
    {"Vang_Q1_encounter02", "Drop by Drop", -1},
    {"__Vang_Q1_warehouse", "Drop by Drop", -1},
    {"__Vang_Q3", "Drop by Drop", -1},
    {"__Amber_Q2", "Drop by Drop", -1},
    {"Hugo_Q1", "Message to the Masses", -1},
    {"Grant_Q1", "The First Head of Cerberus", -1},
    {"Grant_Q2", "The Second Head of Cerberus", -1},
    {"Grant_Q3", "The Third Head of Cerberus", -1},
    {"__Grant_Q3_Bandits", "The Second Head of Cerberus", -1},
    {"__HideSurv020", "Ram on Heaven's Door", -1},
    {"Tavin_Q1", "Bleach with a Vengeance", -1},
    {"__Encounter_SurvivorFighter_Start", "A Tough Nut to Crack", -1},
    {"__Encounter_SurvivorFighter_End", "A Tough Nut to Crack", -1},
    {"__HideChurchDoors", "Sacred Silence", -1},
    {"__GoToPolicestationTest", "On the Road", -1},
    {"__SinamoiChitChat_001", "Sacred Silence", -1},
    {"__SinamoiChitChat_002", "Keep the Faith", -1},
    {"__SinamoiChitChat_003", "Lady in Trouble", -1},
    {"__SinamoiChitChat_004", "Faith Will Move Mountains", -1},
    {"__MatuteroPackage_WaterfallFight", "Chasing Shadows", -1},
    {"Mongina_Q1", "Remains of the Damned", -1},
    {"Sam_Q1", "A Wounded Crank", -1},
    {"__Sam_Q2", "A Wounded Crank", -1},
    {"__Nick_Q3", "Spy Game", -1},
    {"__Nikolai_Q3", "A Voice from Above the Sky", -1},
    {"__Monica_Q1_End", "Nighthawk", -1},
    {"Otha_Q1", "Bridge too far", -1},
    {"Otha_Q2", "Second Aid", -1},
    {"__Otha_hide", "Second Aid", -1},
    {"__Otha_ZombieBoss", "Chasing Shadows", -1},
    {"__Carlos_Q1", "Cold Stone", -1},
    {"__Carlos_Hide", "Welcome to the jungle", -1},
    {"FixingTheGate_Q1", "The Dead in the Fishing Net", -1},
    {"Loren_Q1", "Blood in the Tropics", -1},
    {"__Loren_Q1_RobinStory", "Welcome to the jungle", -1},
    {"Loren_Q2", "Weeds", -1},
    {"Brian_Q1", "Ashes of Humanity", -1},
    {"Carter_Q1", "Death Wish", -1},
    {"__Carter_Q1_initiation", "Welcome to the jungle", -1},
    {"Chris_Q1", "Fallen Angel", -1},
    {"__Chris_Q1_Initiation", "Welcome to the jungle", -1},
    {"Makimbah_Q1", "A Matter of Honor", -1},
    {"Claire_Q1", "Little Prince", -1},
    {"Amanda_Q1", "Show Must Go On", -1},
    {"Dwight_Q1", "Visit to the Pub", -1},
    {"__Dwight_Q1_stairs", "Welcome to the jungle", -1},
    {"__Dwight_Q2_ShopOpened", "Visit to the Pub", -1},
    {"Ethan_Q1", "Light is Life", -1},
    {"Pono_Q1", "Feeding the Multitude", -1},
    {"__Act3B_PortalActive", "River Trip", -1},
    {"__AbandonVillageGate", "Welcome to the jungle", -1},
    {"__CameraBungalowOpen", "Welcome to the jungle", -1},
    {"__Encounter1_Fuel_Bandits", "Welcome to the jungle", -1},
    {"__Encounter2_Camp_Bandits", "Welcome to the jungle", -1},
    {"__enc_NPC_001_Start", "Welcome to the jungle", -1},
    {"__enc_NPC_001_End", "Welcome to the jungle", -1},
    {"__enc_TRAP_004_Start", "Welcome to the jungle", -1},
    {"__enc_TRAP_004_End", "Welcome to the jungle", -1},
    {"__enc_Psycho_001_Start", "Welcome to the jungle", -1},
    {"__enc_CaveCamp_Start", "Welcome to the jungle", -1},
    {"__enc_HostileCampBig_Start", "Welcome to the jungle", -1},
    {"ACT3B_WestScientists", "Rats in the Lab", -1},
    {"__Aafter_ACT3B_WestScientists", "Rats in the Lab", -1},
    {"ACT3B_WestTechnican", "Power Slaves", -1},
    {"ACT3B_WestChemicals", "Substance of Matter", -1},
    {"ACT3B_WestInfecteds", "Rotting Flesh", -1},
    {"Lachance_Q1", "Insect Repellent", -1},
    {"Nguyen_Q1", "Where is my pineapple?", -1},
    {"Nguyen_Q2", "Wet Job", -1},
    {"Connor_Q1", "Deus ex Machina", -1},
    {"Monroe_Q1", "Scran's not for the Dead", -1},
    {"Monroe_Q2", "Blood Compound", -1},
    {"__Monroe_Q2", "Blood Compound", -1},
    {"Scientist005_Q1", "Danse Macabre", -1},
    {"Scientist005_Q3", "No Sign of Life", -1},
    {"Scientist005_Q2", "The Dead don't Eat Crackers", -1},
    {"Scientist005_Q4", "Message of Love", -1},
    {"Warrior_Q1", "Dreamtime", -1},
    {"__EscortYerama_zombie_001", "Sacred Place", -1},
    {"__EscortYerama_zombie_002", "Sacred Place", -1},
    {"__EscortYerama_zombie_003", "Sacred Place", -1},
    {"__BarricadeDoor_001", "River Trip", -1},
    {"__WillySpeaker", "River Trip", -1},
    {"__Scientist005_hide", "Message of Love", -1},
    {"__Magazine_gate", "River Trip", -1},
    {"__ACT3C_YeremaEscort_001", "Heart of Darkness", -1},
    {"__ACT3C_YeremaEscort_002", "Heart of Darkness", -1},
    {"__ACT3C_YeremaEscort_003", "Heart of Darkness", -1},
    {"__ACT3C_YeremaEscort_004", "Heart of Darkness", -1},
    {"__Use_Mine_001", "Chasing the White Rabbit", -1},
    {"__Use_Mine_002", "Chasing the White Rabbit", -1},
    {"__Use_Mine_003", "Chasing the White Rabbit", -1},
    {"Kevin_Q1", "Locked armory", -1},
    {"Angel_Q1", "Banoi Butcher", -1},
    {"__Angel_Q1_After", "Banoi Butcher", -1},
    {"__MovePrisoner008", "Banoi Butcher", -1},
    {"Dreyfus_Q1", "Acid Funk", -1},
    {"___ACT4B_DealerPackage_after", "Acid Funk", -1},
    {"Harland_Q1", "Painful Insanity", -1},
    {"__Harland_Q1_after", "Painful Insanity", -1},
    {"__Hide_Ammo_DZ", "Full Metal Jacket", -1},
    {"__Sewers_HideJoseph", "Let the Waters Flow", -1},
    {"__ACT2B_CityHall_PolicemanLesson", "Let the Waters Flow", -1},
    {"Policeman_Q1", "Guard on Duty", -1},
    {"__ACT2B_MayorCase", "Leader of the Rats", -1},
    {"__ACT2B_Body", "Bitter Return", -1},
    {"ACT2B_KillMayor", "Big Daddy, Where Are You?", -1},
    {"__HotelProlog_side", "HotelProlog side", -1},
    {"__FalingGuy", "FalingGuy", -1},
    {"__Tutorial_Flashlight_END", "Tutorial Flashlight END", -1},
    {"__Market_Safe_Paint", "Supermarket Journey", -1},
    {"__Market_CorridorZombies", "Supermarket Journey", -1},
    {"__Market_ZombiesInRoom", "Supermarket Journey", -1},
    {"__Skull_Orange_Start", "Supermarket Journey", -1},
    {"__Skull_Green_Actv", "Chaos Overture", -1},
    {"__Shotgun", "Supermarket Journey", -1},
    {"__Intercom_004", "Born to be Wild", -1},
    {"__Intercom_005", "Born to be Wild", -1},
    {"__Intercom_007", "Born to be Wild", -1},
    {"__Intercom_008", "Born to be Wild", -1},
    {"__Intercom_009", "Born to be Wild", -1},
    {"__Intercom_010", "Born to be Wild", -1},
    {"Ryders_QF00", "Ryder's Campaign", -1},
    {"Ryders_QF01", "Emily", -1},
    {"Ryders_QF02", "Escape Route", -1},
    {"Ryders_QF03", "Undead Out", -1},
    {"Ryders_QF04", "Safe Trip", -1},
    {"Ryders_QF05", "Fly Away", -1},
    {"RW_FINAL", "Fly Away", -1},
    {"TestEnemy_locker", "TestEnemy locker", -1},
    {"TestMapBalance_locker", "TestMapBalance locker", -1},
    {"TMB_Resort", "TMB Resort", -1},
    {"TMB_Prison", "TMB Prison", -1},
    {"TestMapDI_locker", "TestMapDI locker", -1},
    {"Escort", "Escort", -1},
    {"Drive", "Drive", -1},
    {"HeavyObjects", "HeavyObjects", -1},
    {"Use/Kill", "Use/Kill", -1},
    {"MF_TEST", "MF TEST", -1},
    {"Move/Teleport", "Move/Teleport", -1},
    {"Carry", "Carry", -1},
    {"VirtualSwitch", "VirtualSwitch", -1},
    {"Fill/Area", "Fill/Area", -1},
    {"Hide_AIDeadBodySpawBoxAuto", "Hide AIDeadBodySpawBoxAuto", -1},
    {"LP", "LP", -1},
};
inline constexpr LevelEntry kLevels[] = {
    {"Act1A", "Resort"},
    {"Act2A", "City of Moresby"},
    {"Act3A", "Jungle"},
    {"Act3B", "Laboratory"},
    {"Act3C", "Tomb of Natives"},
    {"Act4A", "The Roof"},
    {"Act4B", "Prison"},
    {"BuildingInterior", "Abandoned house"},
    {"CityHallA", "City Hall Part 1"},
    {"CityHallB", "City Hall Part 2"},
    {"Hotel", "Prologue"},
    {"Market", "Supermarket"},
    {"ParkingLot", "Hotel"},
    {"PoliceStation", "Police Station"},
    {"RWhite", "Ryder Campaign - 3 - Prison"},
    {"RWhite_City", "Ryder Campaign - 2 - City"},
    {"RWhite_Jungle", "Ryder Campaign - 1 - Jungle"},
    {"Sewers", "Sewers"},
    {"TestMapDI", "Test Map (TestMapDI)"},
    {"Tunnels", "Tunnels"},
    {"Warehouse", "Warehouse (Warehouse)"},
    {"arena_a", "Arena A"},
    {"arena_b", "Arena B"},
    {"arena_c", "Arena C"},
    {"arena_d", "Arena D"},
    {"arena_lobby", "Arena Lobby"},
};
} // namespace DeadIslandData
